name: build
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}
      - name: Install Dependencies
        run: yarn
      - name: Run tests
        run: CI=true yarn test
  dummy-check:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Dummy Step
        run: echo "success"
